import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Scents Note Admin</title>
        <meta name="description" content="Generated by create Scents Note" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main></main>
    </>
  );
}
